// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGo-g4HzU0bN7lvEVts5QSRKdKClUo0Uw',
    appId: '1:566199166568:web:c6fe79520ebb5f7945bddd',
    messagingSenderId: '566199166568',
    projectId: 'task-manager-dfb72',
    authDomain: 'task-manager-dfb72.firebaseapp.com',
    storageBucket: 'task-manager-dfb72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgtXMBIxkbjNqNrwgVOxPATv0mgp5_UZI',
    appId: '1:566199166568:android:5e4f34ce033518a645bddd',
    messagingSenderId: '566199166568',
    projectId: 'task-manager-dfb72',
    storageBucket: 'task-manager-dfb72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlOsUKR5m0g-mLWWzfohSTrrtBWaQvw-U',
    appId: '1:566199166568:ios:b8a8d563b3b55cde45bddd',
    messagingSenderId: '566199166568',
    projectId: 'task-manager-dfb72',
    storageBucket: 'task-manager-dfb72.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlOsUKR5m0g-mLWWzfohSTrrtBWaQvw-U',
    appId: '1:566199166568:ios:b8a8d563b3b55cde45bddd',
    messagingSenderId: '566199166568',
    projectId: 'task-manager-dfb72',
    storageBucket: 'task-manager-dfb72.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGo-g4HzU0bN7lvEVts5QSRKdKClUo0Uw',
    appId: '1:566199166568:web:167e5c53386bebee45bddd',
    messagingSenderId: '566199166568',
    projectId: 'task-manager-dfb72',
    authDomain: 'task-manager-dfb72.firebaseapp.com',
    storageBucket: 'task-manager-dfb72.firebasestorage.app',
  );
}
